plugins { id 'com.android.application' }
android {
    namespace 'fr.piika.pupdown'
    compileSdk 34
    defaultConfig {
        applicationId 'fr.piika.pupdown'
        minSdk 24
        targetSdk 34
        versionCode Integer.parseInt(System.getenv('VERSION_CODE') ?: '1')
        versionName "1.0." + (System.getenv('VERSION_CODE') ?: '1')
    }
    signingConfigs {
        release {
            storeFile file('pupdown.jks')
            storePassword 'pupdown123'
            keyAlias 'pupdown'
            keyPassword 'pupdown123'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}
dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
}
